# Generated by Django 5.2.1 on 2025-05-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_supportrequest_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='faq_videos/'),
        ),
    ]
